# Generated by Django 6.0 on 2026-01-06 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('NB', 'Notebook'), ('CAM', 'Câmera/Webcam'), ('MIC', 'Microfone'), ('CX', 'Caixa de Som'), ('CAB', 'Cabos/Adaptadores'), ('OUT', 'Outros')], max_length=3)),
                ('patrimonio', models.CharField(max_length=50, unique=True, verbose_name='N° Patrimônio')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Em estoque?')),
            ],
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Assunto da Reunião')),
                ('data_reuniao', models.DateField()),
                ('hora_teste', models.TimeField(verbose_name='Início do Teste')),
                ('hora_inicio', models.TimeField(verbose_name='Início da Reunião')),
                ('local', models.CharField(max_length=100)),
                ('link_reuniao', models.URLField(blank=True, max_length=500, null=True)),
                ('solicitante', models.CharField(help_text='Nome ou Seção', max_length=100)),
                ('status', models.CharField(choices=[('AGENDA', 'Agendada (Pendente)'), ('REALIZADA', 'Realizada com Sucesso'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('equipamentos', models.ManyToManyField(blank=True, to='reservas.equipamento', verbose_name='Equipamentos Utilizados')),
                ('tecnico_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'ordering': ['data_reuniao', 'hora_inicio'],
            },
        ),
    ]
